#!/bin/bash

I=`dpkg -l | grep "imagemagick"`
if [ -n "$I" ]
then
   echo imagemagick installed
else
   sudo apt-get install imagemagick -y
fi

start() {
  local fullname="$1"
  local filename=`basename "$1"`
  local fileext="${filename##*.}"
  local formatfile=`file "$1" -b --mime-type`;
  if  [[ $formatfile = "image/jpeg" || $formatfile = "image/png"  ]]
    then
      local width=`identify -format "%w" "$1"`
      if [[ $width -gt 2000 ]]
        then
          convert $fullname -resize 2000 -quality 75 $fullname
      else
          convert $fullname -quality 75 $fullname
      fi
  fi
}

scan() {
  local x;
  for e in "$1"/*; do
    x=${e##*/}
    if [ -d "$e" -a ! -L "$e" ]
    then
      scan "$e"
    else
      start "$e"
    fi
  done
}

[ $# -eq 0 ] && dir=`pwd` || dir=$@

scan "$dir"
